port: 3000
jwtSecret: ""
jwtRefreshSecret: ""
storage:
  driver: local
  uploadDir: data/uploads
  # s3:
  #   endpoint: http://localhost:9000
  #   region: us-east-1
  #   bucket: lighttickets
  #   accessKeyId: minioadmin
  #   secretAccessKey: minioadmin
  #   forcePathStyle: true
  #   presignExpiry: 300
